version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
    - 1.0.63
  - dependency-name: redis
    versions:
    - 0.19.0
  - dependency-name: rocket
    versions:
    - 0.4.6
  - dependency-name: rocket_codegen
    versions:
    - 0.4.6
