[package]
authors = ["Aaron Power <theaaronepower@gmail.com>"]
name = "tokei_rs"
version = "0.1.0"
edition = "2018"

[dependencies]
badge = "0.2"
lazy_static = "1"
mime = "0.3"
r2d2 = "0.8"
rocket_codegen = "0.4"
tokei = "11"
dotenv = "0.15"
rocket = "0.4"
tempfile = "3.1.0"
failure = "0.1.8"
serde_json = "1.0.64"
percent-encoding = "2.1.0"
redis = "0.15.1"
r2d2_redis = "0.13.0"
log = "0.4.8"
