[package]
authors = ["Erin Power <xampprocky@gmail.com>"]
name = "tokei_rs"
version = "0.1.0"
edition = "2018"

[dependencies]
badge = "0.3.0"
lazy_static = "1.4.0"
mime = "0.3.16"
tokei = "11"
dotenv = "0.15.0"
tempfile = "3.2.0"
serde = "=1.0.126"
serde_json = "=1.0.64"
percent-encoding = "2.1.0"
log = "0.4.14"
once_cell = "1.7.2"
parking_lot = "0.11.1"
cached = "0.23.0"
actix-web = "3.3.2"
actix-http = "2.2.0"
either = "1.6.1"
eyre = "0.6.5"
env_logger = "0.8.4"
